[package]
name = "orion-macos-system-audio"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
publish = false

[dependencies]
objc2 = "0.6.2"
objc2-core-audio = { version = "0.3.2", default-features = false, features = ["std", "AudioHardware", "objc2", "objc2-core-audio-types", "objc2-foundation"] }
objc2-core-audio-types = "0.3.2"
objc2-core-foundation = { version = "0.3.2", features = ["CFArray", "CFDictionary", "CFNumber", "CFString"] }
objc2-foundation = { version = "0.3.2", features = ["NSArray", "NSObjCRuntime", "NSUUID"] }
rtrb = "0.4.0"
